export const dateFinder = (createdAt) => {
	const newDate = new Date(createdAt);
	var month = new Array();
	month[0] = "Jan";
	month[1] = "Feb";
	month[2] = "March";
	month[3] = "April";
	month[4] = "May";
	month[5] = "June";
	month[6] = "July";
	month[7] = "Aug";
	month[8] = "Sept";
	month[9] = "Oct";
	month[10] = "Nov";
	month[11] = "Dec";
	const year = newDate.getFullYear();
	const months = month[newDate.getMonth()];
	const day = newDate.getDate();
	const date2 = months + " " + day + ", " + year;
	return date2.toString();
};
